sudo: required
language: generic

matrix:
  include:
   - dist: xenial
     env: ROSDISTRO=kinetic
     os: linux
     arch: amd64

   - dist: xenial
     env: ROSDISTRO=kinetic
     os: linux
     arch: arm64

   - dist: bionic
     env: ROSDISTRO=melodic
     os: linux
     arch: amd64

   - dist: bionic
     env: ROSDISTRO=melodic
     os: linux
     arch: arm64

branches:
  only:
    - master

compiler:
  - gcc

install:
  - cd
  - git clone https://github.com/linorobot/rosme
  - cd rosme
  - sudo ./install

notifications:
  email:
  - jimenojmm@gmail.com
