#!/usr/bin/env bash

set -e

ARCH=$(uname -i)
RELEASE=$(lsb_release -c -s)
ROSDISTRO=foxy
locale  # check for UTF-8

sudo apt update && sudo apt install locales
sudo locale-gen en_NZ en_NZ.UTF-8
sudo update-locale LC_ALL=en_NZ.UTF-8 LANG=en_NZ.UTF-8
export LANG=en_NZ.UTF-8

locale  # verify settings
echo Installing ros-$ROSDISTRO
sudo apt update
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
sudo apt -y update
sudo apt -y install ros-$ROSDISTRO-desktop
    echo "Installing ROS-$ROSDISTRO Desktop"
source /opt/ros/$ROSDISTRO/setup.bash
echo "source /opt/ros/$ROSDISTRO/setup.bash" >> ~/.bashrc
source ~/.bashrc 
sudo apt install -y python3-pip
pip3 install -U argcomplete

echo ""
echo "ROS $(rosversion -d) Installation Done!"

